In [1]:
#transposing without copying 

import torch 
import torchvision

In [2]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [3]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [4]:
points_t = points.t()

In [5]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [6]:
id(points.storage()) == id(points_t.storage())

True

In [11]:

points.stride()

(2, 1)

In [12]:

points_t.stride()

(1, 2)

In [13]:
points.is_contiguous()

True

In [14]:
points_t.is_contiguous()

False

In [15]:
points_t.contiguous()

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [16]:
id(points.storage()) == id(points_t.storage())

True

In [17]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [18]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [19]:
points_t.contiguous()

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [21]:
points_t.is_contiguous()

False